### ISSUE TITLE
Package Update Request

### ISSUE THREAD

**Issue by ngoguened** [dgrtwo/unvotes#1]
Hello Dr. Robinson,

Professor Çetinkaya-Rundel and I have found UN voting data from 2019 and earlier. We would like to know if there is any interest in updating this package.

**Comment by dgrtwo** [comment]
I'd be very interested in a PR that updates it!

Preferably you could do it in a similar format to how it's currently done in data-raw?

https://github.com/dgrtwo/unvotes/blob/master/data-raw/un-data.R

**Comment by ngoguened** [comment]
Thank you!

We are beginning to work on it but will not close the issue until we have a pull request.
